### ISSUE TITLE
Differences from aurelian/ruby-stemmer?

### ISSUE THREAD

**Issue by hangsu** [ankane/mittens#2]
Thanks for making this!

Are there any fundamental differences between this library and [aurelian/ruby-stemmer](https://github.com/aurelian/ruby-stemmer)? (other than being recent and maintained, of course)

Were there specific needs you were trying to solve?

I'm eager to give this a try.

**Comment by ankane** [comment]
Hey @hangsu, the main differences are what you mentioned - I just wanted one that's maintained (`ruby-stemmer` also ships precompiled gems for Windows, which this doesn't).

I may eventually switch to using FFI so it can be used with JRuby as well.
